name: Docker Image CI

on:
  push

env:
  DOCKER_HUB: registry.hub.docker.com
  DOCKER_IMAGE_NAME: docker
  DOCKER_ORG: zerola
  DOCKER_USERNAME: zeromic
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build the Docker image
        run: docker build -t ${DOCKER_ORG}/${DOCKER_IMAGE_NAME}:${CIRCLE_BRANCH} .
        env:
          CIRCLE_BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
